### ISSUE TITLE
i like this project

### ISSUE THREAD

**Issue by ghost** [ZeusHay/Synapse-X-Infinity#1]
i think this ui is good, its better than some other ones i know and i just have a couple questions.

- will there be quick access to execute/inject scripts on the home?
- will you add your own custom scripts in the script hub to spice it up? (because i see some extra spaces)
- will the ui have smooth animations after its done?

and thats basically all, i hope you finish this, and im going to be using it for now on.
have a nice day/night.

P.S. if there is a updated required, the dll loading goes on a loop, i dont know if you want this or not but if you dont want it i have the idea of making it red and then close after a couple of seconds, pretty simple and you can do it

**Comment by ZeusHay** [comment]
> Will there be quick access to execute/inject scripts on the home?

Regarding the Dashboard, I intend to use it in two ways, the first is to post the news of the update but in a lively way, in the sense of transitions, etc, and also use the space to alert users about general news, and in a future project, even add news there, but for this, I need to see the best way to do without causing problems or making the project too heavy.

> Will you add your own custom scripts in the script hub to spice it up? (because i see some extra spaces)

Yes, I will, I will divide the menu in a little different design, I intend to add the most popular menus on the home page, and underneath, separate the games, like this:

![](https://cdn.discordapp.com/attachments/870035305368014949/882874617981706280/unknown.png)

(In the big pop-ups I will probably add the scripts that users look for most or something like that, and in the small pop-ups, it will be the tab with the images of the games, and the scripts for it.

> Will the ui have smooth animations after its done?

Yes, yes, I will study further and see what I can do to create smooth animations to add to the project in the future.

> P.S. if there is a updated required, the dll loading goes on a loop, i dont know if you want this or not but if you dont want it i have the idea of making it red and then close after a couple of seconds, pretty simple and you can do it

This problem was caused by the recent roblox update, the original synapse x library is being updated, so it got "Locked" on that screen...

Have a nice day, afternoon or evening too! :D
Thank you for participating in this project.
