### ISSUE TITLE
transparency issues

### ISSUE THREAD

**Issue by Epikest** [ZeusHay/Synapse-X-Infinity#6]
white where it should be transparent
https://epik.isthebestwaifu.club/kMSNH1w0

**Comment by ZeusHay** [comment]
This kind of problem is caused by the fact that Windows itself doesn't allow edge rounding the way we use it, so we use a library that does that, on some computers it may present this kind of error, maybe in the future I will try to change the rounding method to see if it is possible to get a better look.
