### ISSUE TITLE
UI Crash

### ISSUE THREAD

**Issue by v0d0** [ZeusHay/Synapse-X-Infinity#8]
Every few minutes when using the UI it will sometimes crash, hope this gets fixed.

**Comment by ZeusHay** [comment]
If you have used any ui for synapse, or if you have used ours since the last update, this is the problem, the synapse tools have changed, I recommend that you try the following:

1 - Delete all files from your original synapse folder.
2 - Download synapse from the original site.
3 - After downloading, log into your synapse account.
4 - After that, extract the files from our ui.
5 - Possibly, the problem will be solved.
